
version: 2

models:
    - name: first 
      description: "A starter dbt model"
      config:  
        identifier: food_delivery
        materialized: table 
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique


    - name: second
      description: "A starter dbt model"
      config:     
        identifier: food_delivery
        materialized: view                
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null